import type { Feature, FeatureCollection, LineString, MultiLineString, MultiPolygon, Point, Polygon } from 'geojson';

export type SopProperties = {
  location_id: string;
  display_name?: string;
  street_name?: string | null;
  cross_street?: string | null;
  neighborhood?: string | null;
  midpoint_latitude?: number;
  midpoint_longitude?: number;
  SoPIndex8Norm: number;
  PEDS5Norm: number;
  SAFENorm: number;
  TRAFFIC6Norm: number;
  CONN7Norm: number;
  DENS3Norm: number;
  need_score?: number;
  safety_score?: number;
  hin_signal?: number;
  capital_signal?: number;
  capital_opportunity_signal?: number;
  brownfield_opportunity_signal?: number;
  coordination_opportunity_signal?: number;
  environmental_signal?: number;
  environmental_opportunity_signal?: number;
  environmental_constraint_signal?: number;
  brownfield_signal?: number;
  superfund_signal?: number;
  hin_distance_ft?: number | null;
  capital_distance_ft?: number | null;
  capital_project_id?: string | number | null;
  capital_project_name?: string | null;
  capital_project_stage?: string | null;
  capital_opportunity_basis?: string | null;
  capital_let_date?: string | null;
  capital_ntp_date?: string | null;
  capital_completion_date?: string | null;
  capital_open_date?: string | null;
  brownfield_distance_ft?: number | null;
  brownfield_site_name?: string | null;
  brownfield_proximity_signal?: number;
  superfund_distance_ft?: number | null;
  superfund_site_name?: string | null;
  zoning_primary_group?: string | null;
  zoning_primary_code?: string | null;
  zoning_land_use_mix?: string;
  zoning_codes?: string;
  zoning_residential_context_score?: number | null;
  zoning_industrial_context_score?: number | null;
  zoning_special_review?: boolean;
  zoning_pending?: boolean;
  zoning_pending_bills?: string;
  zoning_sample_count?: number;
  zoning_context_basis?: string;
  zoning_context_score?: number | null;
  complete_streets_match?: boolean;
  complete_streets_distance_ft?: number | null;
  complete_streets_type?: string | null;
  complete_streets_class?: string | null;
  complete_streets_bike_facility?: string | null;
  complete_streets_sidewalk_width?: string | null;
  complete_streets_walking_zone?: string | null;
  complete_streets_policy_notes?: string;
  development_permit_count?: number;
  development_permit_nearest_ft?: number | null;
  development_permit_address?: string | null;
  development_permit_type?: string | null;
  development_permit_issue_date?: string | null;
  development_permit_numbers?: string;
  development_context?: boolean;
  pwd_project_match?: boolean;
  pwd_project_distance_ft?: number | null;
  pwd_project_name?: string | null;
  pwd_project_status?: string | null;
  pwd_project_stage?: 'planned' | 'active' | 'completed' | 'unknown' | null;
  pwd_coordination_context?: boolean;
  transit_stop_count?: number;
  nearest_transit_stop_ft?: number | null;
  nearest_transit_stop_name?: string | null;
  transit_routes?: string;
  crash_count?: number;
  serious_crash_count?: number;
  pedestrian_crash_count?: number;
  bicycle_crash_count?: number;
  floodplain_review?: boolean;
  flood_zone?: string | null;
  historic_review?: boolean;
  historic_district?: string | null;
  bike_network_match?: boolean;
  bike_facility_type?: string | null;
  vacancy_context_percent?: number | null;
  context_review_flags?: string;
  priority_base_score?: number;
  public_screening_score?: number;
  review_adjusted_score?: number;
  review_score_delta?: number;
  planner_adjustment_applied?: boolean;
  priority_strategy?: PriorityStrategy;
  zoning_lens?: ZoningLens;
  feasibility_score?: number;
  priority_score?: number;
  recommendation_id?: string;
  recommendation_type?: string;
  recommendation_title?: string;
  recommendation_action?: string;
  recommendation_rationale?: string;
  recommendation_impact?: 'low' | 'medium' | 'high';
  implementation_effort?: 'low' | 'medium' | 'high' | null;
  cost_band?: '$' | '$$' | '$$$' | null;
  timing_band?: string | null;
  recommendation_evidence?: string;
  recommendation_method?: string;
};

export type SopFeature = Feature<LineString, SopProperties>;
export type SopCollection = FeatureCollection<LineString, SopProperties>;
export type LineCollection = FeatureCollection<LineString | MultiLineString>;
export type PointCollection = FeatureCollection<Point>;
export type PolygonCollection = FeatureCollection<Polygon | MultiPolygon>;

export type Weights = {
  need: number;
  safety: number;
  coordination: number;
};

export type PriorityStrategy = 'need' | 'safety' | 'coordination' | 'balanced' | 'custom';
export type ZoningLens = 'citywide' | 'residential_access' | 'industrial_safety';

export type ExternalData = {
  hin: LineCollection;
  capital: LineCollection;
  environmental: PointCollection;
  completeStreets: LineCollection;
  development: PointCollection;
  pwd: LineCollection;
  transit: PointCollection;
  crashes: PointCollection;
  bike: LineCollection;
};

export type DataSourceRole = 'need' | 'safety' | 'policy' | 'coordination' | 'context' | 'constraint' | 'identification';

export type DataSourceRecord = {
  id: string;
  name: string;
  publisher: string;
  url: string;
  role: DataSourceRole;
  affects_score: boolean;
  refreshed_at: string;
  source_vintage?: string;
  feature_count?: number;
  segment_match_count?: number;
  segment_match_percent?: number;
  method: string;
  limitations: string;
  status: 'ready' | 'unavailable' | 'deferred';
};

export type DataManifest = {
  generated_at: string;
  method_version: string;
  segment_count: number;
  sources: DataSourceRecord[];
};
